TOOLS_DIALOG_ACTIONS_ROOT = $$clean_path($$_PRO_FILE_PWD_/..)
BUILD_ROOT = $$TOOLS_DIALOG_ACTIONS_ROOT/build/tools_dialog_actions_smoke
include($$TOOLS_DIALOG_ACTIONS_ROOT/qt_ui_test.pro)

TARGET = tools_dialog_actions_smoke
DESTDIR = $$BUILD_ROOT/bin
SOURCES -= src/main.cpp
SOURCES += $$TOOLS_DIALOG_ACTIONS_ROOT/smoke/tools_dialog_actions_smoke.cpp

TOOLS_DIALOG_ACTIONS_SOURCES =
for(file, SOURCES): TOOLS_DIALOG_ACTIONS_SOURCES += $$absolute_path($$file, $$TOOLS_DIALOG_ACTIONS_ROOT)
SOURCES = $$TOOLS_DIALOG_ACTIONS_SOURCES

TOOLS_DIALOG_ACTIONS_HEADERS =
for(file, HEADERS): TOOLS_DIALOG_ACTIONS_HEADERS += $$absolute_path($$file, $$TOOLS_DIALOG_ACTIONS_ROOT)
HEADERS = $$TOOLS_DIALOG_ACTIONS_HEADERS

TOOLS_DIALOG_ACTIONS_FORMS =
for(file, FORMS): TOOLS_DIALOG_ACTIONS_FORMS += $$absolute_path($$file, $$TOOLS_DIALOG_ACTIONS_ROOT)
FORMS = $$TOOLS_DIALOG_ACTIONS_FORMS

TOOLS_DIALOG_ACTIONS_RESOURCES =
for(file, RESOURCES): TOOLS_DIALOG_ACTIONS_RESOURCES += $$absolute_path($$file, $$TOOLS_DIALOG_ACTIONS_ROOT)
RESOURCES = $$TOOLS_DIALOG_ACTIONS_RESOURCES

INCLUDEPATH = $$TOOLS_DIALOG_ACTIONS_ROOT/src $$INCLUDEPATH
