#ifndef CALIBRATION_NPOINTCALIBRATIONCONFIGWIDGET_H
#define CALIBRATION_NPOINTCALIBRATIONCONFIGWIDGET_H

#include "calibration/CalibrationMethodRegistry.h"

#include <QJsonObject>
#include <QMap>
#include <QVector>

class QComboBox;
class QDoubleSpinBox;
class QLineEdit;
class QLabel;
class QPushButton;
class QTableWidget;
class QSpinBox;
class QToolButton;

class NPointCalibrationConfigWidget final : public CalibrationMethodConfigWidget
{
public:
    explicit NPointCalibrationConfigWidget(QWidget *parent = nullptr);

    CalibrationDraft draft(QString *errorMessage = nullptr) const override;
    void setProducerSnapshots(
            const QVector<CalibrationProducerSnapshot> &snapshots) override;
    void setLatestPhysicalSample(bool valid,
                                 double x,
                                 double y,
                                 double angleDeg) override;
    QString captureImageProducerId() const override;
    bool captureCurrentSample(QString *errorMessage = nullptr) override;
    QVector<QLineF> completedTranslationSegments() const override;
    int completedTranslationSampleCount() const override;
    int translationSampleCount() const override;

    // Reserved online-acquisition contract. The descriptors are exposed through
    // draft().parameters but are intentionally not consumed by the solver yet.
    QJsonObject captureBindings() const;
    void setCaptureBinding(const QString &fieldKey, const QJsonObject &binding);

    // Reusable N-point configuration. This intentionally excludes sampled
    // coordinates and transient communication/runtime state.
    QJsonObject persistentSettings() const;
    bool restorePersistentSettings(const QJsonObject &settings,
                                   QString *errorMessage = nullptr);

    // Unfinished sampling state. Completion is stored explicitly per row so
    // that a valid all-zero calibration point is not mistaken for an empty row.
    QJsonObject draftState() const;
    bool restoreDraftState(const QJsonObject &state,
                           QString *errorMessage = nullptr);
    int completedSampleCount() const;
    int sampleCount() const;

    // The region geometry is generated by the HALCON solver.  The widget only
    // displays the latest summary and never reimplements region generation.
    void setRegionSummary(int validRegionPointCount,
                          int safeRegionPointCount,
                          const QString &message,
                          const QString &state = QStringLiteral("idle"));

private:
    void fillDefaultGrid();
    QString sampleTypeForRow(int row) const;
    bool importPoints(QTableWidget *editor,
                      int *translationCount,
                      int *rotationCount,
                      QVector<bool> *completed,
                      bool *retryRequested);
    void exportPoints(const QTableWidget *editor,
                      int translationCount);
    void editPoints();
    void setParameterMode(bool showAll);
    void applyImageProducerBinding(const QString &fieldKey, int producerIndex);
    void applyPhysicalCommunicationBinding(const QString &fieldKey, bool enabled);
    void syncLegacyImageProducer();
    void updateCaptureModeUi();
    void updateCaptureBindingUi(const QString &fieldKey);
    void resetCaptureCursorToFirstIncomplete();
    QVector<CalibrationSample> samplesFromTable(QString *errorMessage) const;

    QComboBox *m_imageProducer = nullptr;
    QSpinBox *m_translationCount = nullptr;
    QSpinBox *m_rotationCount = nullptr;
    QTableWidget *m_sampleTable = nullptr;
    QDoubleSpinBox *m_rmseLimit = nullptr;
    QDoubleSpinBox *m_maxErrorLimit = nullptr;
    QLabel *m_sampleStatus = nullptr;
    QPushButton *m_basicButton = nullptr;
    QPushButton *m_allButton = nullptr;
    QPushButton *m_triggerCaptureButton = nullptr;
    QPushButton *m_manualCaptureButton = nullptr;
    QWidget *m_captureSubscriptionWidget = nullptr;
    QWidget *m_physicalCoordinateCard = nullptr;
    QWidget *m_runtimeParametersCard = nullptr;
    QWidget *m_qualityCard = nullptr;
    QWidget *m_effectiveRegionCard = nullptr;
    QDoubleSpinBox *m_referenceX = nullptr;
    QDoubleSpinBox *m_referenceY = nullptr;
    QDoubleSpinBox *m_offsetX = nullptr;
    QDoubleSpinBox *m_offsetY = nullptr;
    QComboBox *m_movePriority = nullptr;
    QSpinBox *m_directionChangeCount = nullptr;
    QDoubleSpinBox *m_referenceAngle = nullptr;
    QDoubleSpinBox *m_angleOffset = nullptr;
    QSpinBox *m_calibrationOrigin = nullptr;
    QComboBox *m_cameraMotionMode = nullptr;
    QComboBox *m_degreesOfFreedom = nullptr;
    QComboBox *m_weightFunction = nullptr;
    QSpinBox *m_weightCoefficient = nullptr;
    QDoubleSpinBox *m_safeMarginPx = nullptr;
    QLabel *m_validRegionPointCount = nullptr;
    QLabel *m_safeRegionPointCount = nullptr;
    QLabel *m_regionGenerationStatus = nullptr;
    QMap<QString, QLineEdit *> m_captureBindingEdits;
    QMap<QString, QToolButton *> m_captureBindingButtons;
    QMap<QString, QJsonObject> m_captureBindingValues;
    QVector<CalibrationProducerSnapshot> m_snapshots;
    bool m_physicalSampleValid = false;
    double m_physicalX = 0.0;
    double m_physicalY = 0.0;
    double m_physicalAngle = 0.0;
    int m_nextCaptureRow = 0;
    QVector<bool> m_sampleCompleted;
    bool m_pointEditorOpen = false;
};

#endif // CALIBRATION_NPOINTCALIBRATIONCONFIGWIDGET_H
